Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
bw = LMERegression(df, y='Log power', treatment='stim', group='mouse')
bw.fit(add_data=False)
bw.plot().display()


bw.posterior
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_6142/309491036.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mbw[0m [0;34m=[0m [0mLMERegression[0m[0;34m([0m[0mdf[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;34m'Log power'[0m[0;34m,[0m [0mtreatment[0m[0;34m=[0m[0;34m'stim'[0m[0;34m,[0m [0mgroup[0m[0;34m=[0m[0;34m'mouse'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mbw[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0madd_data[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mbw[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mdisplay[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/bayes_window/lme.py[0m in [0;36mfit[0;34m(self, do_make_change, add_interaction, add_data, formula, add_group_intercept, add_group_slope, add_nested_group, **kwargs)[0m
[1;32m     43[0m         [0;31m# dehumanize all columns and variable names for statsmodels:[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     44[0m         [self.window.data.rename({col: col.replace(" ", "_")}, axis=1, inplace=True) for col in
[0;32m---> 45[0;31m          self.window.data.columns]
[0m[1;32m     46[0m         [0mself[0m[0;34m.[0m[0mwindow[0m[0;34m.[0m[0my[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mwindow[0m[0;34m.[0m[0my[0m[0;34m.[0m[0mreplace[0m[0;34m([0m[0;34m" "[0m[0;34m,[0m [0;34m"_"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     47[0m         [0mself[0m[0;34m.[0m[0mwindow[0m[0;34m.[0m[0mgroup[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mwindow[0m[0;34m.[0m[0mgroup[0m[0;34m.[0m[0mreplace[0m[0;34m([0m[0;34m" "[0m[0;34m,[0m [0;34m"_"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas/core/generic.py[0m in [0;36m__getattr__[0;34m(self, name)[0m
[1;32m   5485[0m         ):
[1;32m   5486[0m             [0;32mreturn[0m [0mself[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5487[0;31m         [0;32mreturn[0m [0mobject[0m[0;34m.[0m[0m__getattribute__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   5488[0m [0;34m[0m[0m
[1;32m   5489[0m     [0;32mdef[0m [0m__setattr__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m:[0m [0mstr[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m [0;34m->[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'data'
AttributeError: 'DataFrame' object has no attribute 'data'

